"""OneMore Design Token Exporter — generates theme/token files in 7 formats."""
import json as _json
import re
from pathlib import Path
from typing import Optional

from scripts.core import _load_csv, DATA_DIR

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_foundations():
    """Load all foundation CSVs and return as a dict."""
    return {
        "colors": _load_csv("foundations", "colors.csv"),
        "spacing": _load_csv("foundations", "spacing.csv"),
        "typography": _load_csv("foundations", "typography.csv"),
        "corners": _load_csv("foundations", "corners.csv"),
        "elevation": _load_csv("foundations", "elevation.csv"),
    }


def _keyword_to_slug(keyword: str) -> str:
    """Convert camelCase keyword to kebab-case slug."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", keyword)
    return s.lower().replace("_", "-")


def _keyword_to_snake(keyword: str) -> str:
    """Convert camelCase keyword to snake_case."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", keyword)
    return s.lower()


def _camel_to_title(keyword: str) -> str:
    """Convert camelCase to Title Case for Swift/Dart identifiers."""
    # Keep the camelCase as-is for code identifiers
    return keyword


def _weight_to_css(weight: str) -> str:
    """Map weight name to CSS numeric weight."""
    mapping = {
        "Regular": "400",
        "Medium": "500",
        "Semibold": "600",
        "Bold": "700",
        "Heavy": "800",
        "Black": "900",
        "Light": "300",
        "Thin": "200",
        "Ultralight": "100",
    }
    return mapping.get(weight, "400")


def _weight_to_flutter(weight: str) -> str:
    """Map weight name to Flutter FontWeight."""
    mapping = {
        "Regular": "FontWeight.w400",
        "Medium": "FontWeight.w500",
        "Semibold": "FontWeight.w600",
        "Bold": "FontWeight.w700",
        "Heavy": "FontWeight.w800",
        "Black": "FontWeight.w900",
        "Light": "FontWeight.w300",
        "Thin": "FontWeight.w200",
        "Ultralight": "FontWeight.w100",
    }
    return mapping.get(weight, "FontWeight.w400")


# ---------------------------------------------------------------------------
# Color categorization helpers
# ---------------------------------------------------------------------------

def _categorize_colors(colors):
    """Split colors into system colors, grays, labels, backgrounds, fills, separators, and web."""
    system = []
    grays = []
    labels = []
    backgrounds = []
    fills = []
    separators = []
    web = []
    other = []

    for c in colors:
        kw = c["keyword"]
        role = c.get("semantic_role", "")
        platform = c.get("platform", "all")

        if platform == "web":
            web.append(c)
        elif kw.startswith("systemGray"):
            grays.append(c)
        elif kw.startswith("system") and not kw.startswith("systemGray"):
            if "Background" in kw or "Grouped" in kw:
                backgrounds.append(c)
            elif "Fill" in kw:
                fills.append(c)
            else:
                system.append(c)
        elif "label" in kw.lower() or "Label" in kw:
            labels.append(c)
        elif "background" in kw.lower() or "Background" in kw:
            backgrounds.append(c)
        elif "fill" in kw.lower() or "Fill" in kw:
            fills.append(c)
        elif "separator" in kw.lower() or "Separator" in kw:
            separators.append(c)
        else:
            other.append(c)

    return {
        "system": system,
        "grays": grays,
        "labels": labels,
        "backgrounds": backgrounds,
        "fills": fills,
        "separators": separators,
        "web": web,
        "other": other,
    }


# ---------------------------------------------------------------------------
# Generator: Tailwind
# ---------------------------------------------------------------------------

def generate_tailwind() -> str:
    data = _load_foundations()
    colors = data["colors"]
    spacing = data["spacing"]
    typography = [t for t in data["typography"] if t.get("platform") == "ios"]
    corners = data["corners"]
    elevation = [e for e in data["elevation"] if e.get("material") == "none"]

    lines = []
    lines.append("/** @type {import('tailwindcss').Config} */")
    lines.append("// Generated by OneMore \u2014 Apple HIG Design Tokens")
    lines.append("module.exports = {")
    lines.append("  theme: {")
    lines.append("    extend: {")

    # --- Colors ---
    lines.append("      colors: {")

    cats = _categorize_colors(colors)

    # Apple system colors
    lines.append("        apple: {")
    for c in cats["system"]:
        name = c["keyword"].replace("system", "").lower()
        lines.append(f"          {name}: {{ light: '{c['light_hex']}', dark: '{c['dark_hex']}' }},")
    lines.append("        },")

    # Grays
    lines.append("        gray: {")
    for c in cats["grays"]:
        idx = c["keyword"].replace("systemGray", "")
        key = idx if idx else "DEFAULT"
        lines.append(f"          '{key}': {{ light: '{c['light_hex']}', dark: '{c['dark_hex']}' }},")
    lines.append("        },")

    # Labels
    lines.append("        label: {")
    for c in cats["labels"]:
        kw = c["keyword"]
        if kw == "label":
            key = "DEFAULT"
        else:
            key = kw.replace("Label", "").replace("label", "")
            key = key[0].lower() + key[1:] if key else "DEFAULT"
            if key == "secondary":
                pass
            elif key == "tertiary":
                pass
            elif key == "quaternary":
                pass
        lines.append(f"          {key}: {{ light: '{c['light_hex']}', dark: '{c['dark_hex']}' }},")
    lines.append("        },")

    # Backgrounds
    lines.append("        bg: {")
    for c in cats["backgrounds"]:
        kw = c["keyword"]
        if kw == "systemBackground":
            key = "DEFAULT"
        elif kw == "secondarySystemBackground":
            key = "secondary"
        elif kw == "tertiarySystemBackground":
            key = "tertiary"
        elif kw == "systemGroupedBackground":
            key = "grouped"
        elif kw == "secondarySystemGroupedBackground":
            key = "groupedSecondary"
        elif kw == "tertiarySystemGroupedBackground":
            key = "groupedTertiary"
        else:
            key = _keyword_to_slug(kw)
        lines.append(f"          '{key}': {{ light: '{c['light_hex']}', dark: '{c['dark_hex']}' }},")
    lines.append("        },")

    lines.append("      },")

    # --- Spacing ---
    lines.append("      spacing: {")
    for s in spacing:
        kw = s["keyword"]
        # Use px values for web
        lines.append(f"        'apple-{kw}': '{s['value_px']}px',")
    lines.append("      },")

    # --- Font Size ---
    lines.append("      fontSize: {")
    for t in typography:
        slug = _keyword_to_slug(t["keyword"])
        size = t["size_pt"]
        lh = t["line_height"]
        weight = _weight_to_css(t["weight"])
        lines.append(f"        '{slug}': ['{size}px', {{ lineHeight: '{lh}px', fontWeight: '{weight}' }}],")
    lines.append("      },")

    # --- Border Radius ---
    lines.append("      borderRadius: {")
    for c in corners:
        if c["radius_pt"] == "varies":
            continue
        slug = _keyword_to_slug(c["keyword"])
        lines.append(f"        'apple-{slug}': '{c['radius_pt']}px',")
    lines.append("      },")

    # --- Font Family ---
    lines.append("      fontFamily: {")
    lines.append("        apple: ['-apple-system', 'BlinkMacSystemFont', '\"Inter\"', 'system-ui', 'sans-serif'],")
    lines.append("      },")

    # --- Box Shadow ---
    lines.append("      boxShadow: {")
    for e in elevation:
        slug = _keyword_to_slug(e["keyword"])
        blur = e["blur"]
        opacity = e["opacity"]
        offset_y = e["offset_y"]
        lines.append(f"        '{slug}': '0 {offset_y}px {blur}px rgba(0,0,0,{opacity})',")
    lines.append("      },")

    lines.append("    },")
    lines.append("  },")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Generator: CSS
# ---------------------------------------------------------------------------

def generate_css() -> str:
    data = _load_foundations()
    colors = data["colors"]
    spacing = data["spacing"]
    typography = [t for t in data["typography"] if t.get("platform") == "ios"]
    corners = data["corners"]
    elevation = [e for e in data["elevation"] if e.get("material") == "none"]

    lines = []
    lines.append("/* Generated by OneMore \u2014 Apple HIG Design Tokens */")
    lines.append(":root {")

    # Colors (light mode)
    lines.append("  /* Colors */")
    for c in colors:
        slug = _keyword_to_slug(c["keyword"])
        lines.append(f"  --{slug}: {c['light_hex']};")

    lines.append("")

    # Spacing
    lines.append("  /* Spacing */")
    for s in spacing:
        lines.append(f"  --space-{s['keyword']}: {s['value_px']}px;")

    lines.append("")

    # Typography
    lines.append("  /* Typography */")
    lines.append("  --font-apple: -apple-system, BlinkMacSystemFont, \"Inter\", system-ui, sans-serif;")
    for t in typography:
        slug = _keyword_to_slug(t["keyword"])
        lines.append(f"  --text-{slug}: {t['size_pt']}px;")
        lines.append(f"  --lh-{slug}: {t['line_height']}px;")

    lines.append("")

    # Border Radius
    lines.append("  /* Border Radius */")
    for c in corners:
        if c["radius_pt"] == "varies":
            continue
        slug = _keyword_to_slug(c["keyword"])
        lines.append(f"  --radius-{slug}: {c['radius_pt']}px;")

    lines.append("")

    # Shadows
    lines.append("  /* Shadows */")
    for e in elevation:
        slug = _keyword_to_slug(e["keyword"])
        lines.append(f"  --shadow-{slug}: 0 {e['offset_y']}px {e['blur']}px rgba(0,0,0,{e['opacity']});")

    lines.append("}")
    lines.append("")

    # Dark mode
    lines.append("@media (prefers-color-scheme: dark) {")
    lines.append("  :root {")
    lines.append("    /* Colors — dark mode overrides */")
    for c in colors:
        if c["light_hex"] != c["dark_hex"]:
            slug = _keyword_to_slug(c["keyword"])
            lines.append(f"    --{slug}: {c['dark_hex']};")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Generator: SwiftUI
# ---------------------------------------------------------------------------

_SWIFTUI_FONT_MAP = {
    "extraLargeTitle": ".extraLargeTitle",
    "extraLargeTitle2": ".extraLargeTitle2",
    "largeTitle": ".largeTitle",
    "title1": ".title",
    "title2": ".title2",
    "title3": ".title3",
    "headline": ".headline",
    "body": ".body",
    "callout": ".callout",
    "subheadline": ".subheadline",
    "footnote": ".footnote",
    "caption1": ".caption",
    "caption2": ".caption2",
}


def generate_swiftui() -> str:
    data = _load_foundations()
    colors = _categorize_colors(data["colors"])
    spacing = data["spacing"]
    typography = [t for t in data["typography"] if t.get("platform") == "ios"]
    corners = data["corners"]

    lines = []
    lines.append("// Generated by OneMore \u2014 Apple HIG Design Tokens")
    lines.append("import SwiftUI")
    lines.append("")

    # Color extension
    lines.append("extension Color {")
    for c in colors["system"]:
        name = c["keyword"].replace("system", "")
        swift_name = "apple" + name
        lines.append(f'    static let {swift_name} = Color("system{name}")')
    lines.append("    // Note: System colors are built-in to SwiftUI")
    lines.append("    // This file provides custom semantic tokens")
    lines.append("}")
    lines.append("")

    # Font extension
    lines.append("extension Font {")
    for t in typography:
        kw = t["keyword"]
        swift_name = "apple" + kw[0].upper() + kw[1:]
        mapped = _SWIFTUI_FONT_MAP.get(kw, ".body")
        lines.append(f"    static let {swift_name}: Font = {mapped}")
    lines.append("}")
    lines.append("")

    # Spacing struct
    lines.append("struct AppleSpacing {")
    for s in spacing:
        kw = s["keyword"]
        # Convert keyword to valid Swift identifier
        swift_kw = kw.replace("-", "_").replace(" ", "_")
        # Sanitize: if starts with digit, prefix with underscore
        if swift_kw[0].isdigit():
            swift_kw = "_" + swift_kw
        lines.append(f"    static let {swift_kw}: CGFloat = {s['value_pt']}")
    lines.append("}")
    lines.append("")

    # Radius struct
    lines.append("struct AppleRadius {")
    for c in corners:
        if c["radius_pt"] == "varies":
            continue
        kw = c["keyword"].replace("-", "")
        # camelCase
        parts = c["keyword"].split("-")
        swift_kw = parts[0] + "".join(p.capitalize() for p in parts[1:])
        lines.append(f"    static let {swift_kw}: CGFloat = {c['radius_pt']}")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Generator: Flutter
# ---------------------------------------------------------------------------

_CUPERTINO_COLORS = {
    "systemBlue", "systemGreen", "systemIndigo", "systemOrange",
    "systemPink", "systemPurple", "systemRed", "systemTeal", "systemYellow",
}


def generate_flutter() -> str:
    data = _load_foundations()
    colors = data["colors"]
    spacing = data["spacing"]
    typography = [t for t in data["typography"] if t.get("platform") == "ios"]
    corners = data["corners"]

    lines = []
    lines.append("// Generated by OneMore \u2014 Apple HIG Design Tokens")
    lines.append("import 'package:flutter/cupertino.dart';")
    lines.append("")

    # Colors class
    lines.append("class AppleColors {")
    for c in colors:
        kw = c["keyword"]
        if kw in _CUPERTINO_COLORS:
            cupertino_name = kw
            lines.append(f"  static const {kw} = CupertinoColors.{cupertino_name};")
        elif c.get("platform") == "web":
            # Web colors as custom Color
            hex_val = c["light_hex"].lstrip("#")
            if len(hex_val) == 6:
                lines.append(f"  static const Color {kw} = Color(0xFF{hex_val.upper()});")
            else:
                lines.append(f"  static const Color {kw} = Color(0xFF{hex_val[:6].upper()});")
        else:
            hex_val = c["light_hex"].lstrip("#")
            if len(hex_val) <= 6:
                lines.append(f"  static const Color {kw} = Color(0xFF{hex_val.upper()});")
            else:
                # Has alpha
                alpha = hex_val[6:]
                rgb = hex_val[:6]
                lines.append(f"  static const Color {kw} = Color(0x{alpha.upper()}{rgb.upper()});")
    lines.append("}")
    lines.append("")

    # Spacing class
    lines.append("class AppleSpacing {")
    for s in spacing:
        kw = s["keyword"].replace("-", "_")
        if kw[0].isdigit():
            kw = "_" + kw
        lines.append(f"  static const double {kw} = {s['value_pt']};")
    lines.append("}")
    lines.append("")

    # Radius class
    lines.append("class AppleRadius {")
    for c in corners:
        if c["radius_pt"] == "varies":
            continue
        parts = c["keyword"].split("-")
        dart_kw = parts[0] + "".join(p.capitalize() for p in parts[1:])
        lines.append(f"  static const double {dart_kw} = {c['radius_pt']};")
    lines.append("}")
    lines.append("")

    # Typography class
    lines.append("class AppleTypography {")
    for t in typography:
        kw = t["keyword"]
        size = t["size_pt"]
        weight = _weight_to_flutter(t["weight"])
        lines.append(f"  static const TextStyle {kw} = TextStyle(fontSize: {size}, fontWeight: {weight});")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Generator: SCSS
# ---------------------------------------------------------------------------

def generate_scss() -> str:
    data = _load_foundations()
    colors = data["colors"]
    spacing = data["spacing"]
    typography = [t for t in data["typography"] if t.get("platform") == "ios"]
    corners = data["corners"]
    elevation = [e for e in data["elevation"] if e.get("material") == "none"]

    lines = []
    lines.append("// Generated by OneMore \u2014 Apple HIG Design Tokens")

    # Colors
    lines.append("")
    lines.append("// Colors")
    for c in colors:
        slug = _keyword_to_slug(c["keyword"])
        lines.append(f"${slug}: {c['light_hex']};")
        if c["light_hex"] != c["dark_hex"]:
            lines.append(f"${slug}-dark: {c['dark_hex']};")

    # Spacing
    lines.append("")
    lines.append("// Spacing")
    for s in spacing:
        lines.append(f"$space-{s['keyword']}: {s['value_px']}px;")

    # Typography
    lines.append("")
    lines.append("// Typography")
    lines.append('$font-apple: -apple-system, BlinkMacSystemFont, "Inter", system-ui, sans-serif;')
    for t in typography:
        slug = _keyword_to_slug(t["keyword"])
        lines.append(f"$text-{slug}: {t['size_pt']}px;")

    # Border Radius
    lines.append("")
    lines.append("// Border Radius")
    for c in corners:
        if c["radius_pt"] == "varies":
            continue
        slug = _keyword_to_slug(c["keyword"])
        lines.append(f"$radius-{slug}: {c['radius_pt']}px;")

    # Shadows
    lines.append("")
    lines.append("// Shadows")
    for e in elevation:
        slug = _keyword_to_slug(e["keyword"])
        lines.append(f"$shadow-{slug}: 0 {e['offset_y']}px {e['blur']}px rgba(0, 0, 0, {e['opacity']});")

    # Mixins
    lines.append("")
    lines.append("// Mixins")
    lines.append("@mixin apple-dark-mode {")
    lines.append("  @media (prefers-color-scheme: dark) { @content; }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Generator: JSON
# ---------------------------------------------------------------------------

def generate_json() -> str:
    data = _load_foundations()

    result = {
        "generated_by": "OneMore \u2014 Apple HIG Design Tokens",
        "colors": {},
        "spacing": {},
        "typography": {},
        "borderRadius": {},
        "shadows": {},
    }

    for c in data["colors"]:
        result["colors"][c["keyword"]] = {
            "light": c["light_hex"],
            "dark": c["dark_hex"],
        }

    for s in data["spacing"]:
        result["spacing"][s["keyword"]] = int(s["value_pt"])

    for t in data["typography"]:
        result["typography"][t["keyword"]] = {
            "size": int(t["size_pt"]),
            "weight": t["weight"],
            "lineHeight": t["line_height"],
            "platform": t.get("platform", "ios"),
        }

    for c in data["corners"]:
        if c["radius_pt"] == "varies":
            continue
        parts = c["keyword"].split("-")
        key = parts[0] + "".join(p.capitalize() for p in parts[1:])
        result["borderRadius"][key] = int(c["radius_pt"])

    for e in data["elevation"]:
        slug = e["keyword"]
        result["shadows"][slug] = {
            "blur": int(e["blur"]) if e["blur"].isdigit() else e["blur"],
            "opacity": float(e["opacity"]),
            "offsetY": int(e["offset_y"]) if e["offset_y"].lstrip("-").isdigit() else e["offset_y"],
            "color": e["color"],
            "material": e["material"],
        }

    return _json.dumps(result, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Generator: React Native
# ---------------------------------------------------------------------------

def generate_react_native() -> str:
    data = _load_foundations()
    colors = data["colors"]
    spacing = data["spacing"]
    typography = [t for t in data["typography"] if t.get("platform") == "ios"]
    corners = data["corners"]

    lines = []
    lines.append("// Generated by OneMore \u2014 Apple HIG Design Tokens")
    lines.append("import { StyleSheet } from 'react-native';")
    lines.append("")

    # Light colors
    lines.append("export const AppleColors = {")
    for c in colors:
        if c.get("platform") == "web":
            continue
        lines.append(f"  {c['keyword']}: '{c['light_hex']}',")
    lines.append("} as const;")
    lines.append("")

    # Dark colors
    lines.append("export const AppleColorsDark = {")
    for c in colors:
        if c.get("platform") == "web":
            continue
        lines.append(f"  {c['keyword']}: '{c['dark_hex']}',")
    lines.append("} as const;")
    lines.append("")

    # Spacing
    lines.append("export const AppleSpacing = {")
    for s in spacing:
        kw = s["keyword"].replace("-", "_")
        if kw[0].isdigit():
            kw = "_" + kw
        lines.append(f"  {kw}: {s['value_pt']},")
    lines.append("} as const;")
    lines.append("")

    # Radius
    lines.append("export const AppleRadius = {")
    for c in corners:
        if c["radius_pt"] == "varies":
            continue
        parts = c["keyword"].split("-")
        key = parts[0] + "".join(p.capitalize() for p in parts[1:])
        lines.append(f"  {key}: {c['radius_pt']},")
    lines.append("} as const;")
    lines.append("")

    # Typography
    lines.append("export const AppleTypography = StyleSheet.create({")
    for t in typography:
        kw = t["keyword"]
        size = t["size_pt"]
        weight = _weight_to_css(t["weight"])
        lines.append(f"  {kw}: {{ fontSize: {size}, fontWeight: '{weight}' }},")
    lines.append("});")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Export Registry & Main Function
# ---------------------------------------------------------------------------

EXPORT_FORMATS = {
    "tailwind": {"filename": "tailwind.config.js", "generator": generate_tailwind},
    "css": {"filename": "apple-tokens.css", "generator": generate_css},
    "swiftui": {"filename": "AppleTokens.swift", "generator": generate_swiftui},
    "flutter": {"filename": "apple_theme.dart", "generator": generate_flutter},
    "scss": {"filename": "_apple-tokens.scss", "generator": generate_scss},
    "json": {"filename": "apple-tokens.json", "generator": generate_json},
    "react-native": {"filename": "appleTheme.ts", "generator": generate_react_native},
}


def export_tokens(format_name: str, output_dir=None):
    """Export Apple HIG design tokens in the specified format."""
    if format_name not in EXPORT_FORMATS:
        return {"error": f"Unknown format: {format_name}", "available": list(EXPORT_FORMATS.keys())}

    config = EXPORT_FORMATS[format_name]
    content = config["generator"]()

    output_dir = Path(output_dir) if output_dir else Path.cwd()
    output_dir.mkdir(parents=True, exist_ok=True)
    filepath = output_dir / config["filename"]
    filepath.write_text(content, encoding="utf-8")

    return {
        "status": "generated",
        "format": format_name,
        "file": str(filepath),
        "filename": config["filename"],
    }
